[book]
title = "넷평의 개발 노트"
description = "study.dev-notes"
authors = ["netpyoung"]
language = "kr"
multilingual = false
src = "src"

[output.html]
no-section-label = true
site-url = "/dev-notes/"
git-repository-url = "https://github.com/netpyoung/study.dev-notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/netpyoung/study.dev-notes/edit/main/{path}"
