name: Build and deploy GH Pages

## ref: https://github.com/peaceiris/actions-mdbook

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'book.toml'
  workflow_dispatch:

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
      - name: Build mdBook
        run: |
          mdbook build
          touch ./book/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book